# appspec.yml
version: 0.0
os: linux
files:
  - source: dist/
    destination: /var/www/react-vite/
permissions:
  - object: /var/www/react-vite
    pattern: "**"
    owner: nginx
    group: nginx
    mode: 644
  - object: /var/www/react-vite
    owner: nginx
    group: nginx
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root