version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Running pre-build commands...
      - node --version
      - npm --version

  build:
    commands:
      - echo Building the Vite React app...
      - npm run build

  post_build:
    commands:
      - echo Build completed
      - ls -la dist/

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - dist/**
  discard-paths: no