version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the Vite React app...
      - npm run build

artifacts:
  files:
    - appspec.yml
    - scripts/**       # Include your lifecycle scripts
    - dist/**          # Include built frontend files
  discard-paths: no    # Keeps directory structure